[env]
TERM = "xterm-256color"

[general]

working_directory = "C:/Users/daohr"
live_config_reload = true

[window]
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal = {family = "FiraCode Nerd Font Mono", style = "Regular"}

[colors]

[colors.primary]
foreground = "#F1F1F1"
background = "#141C25"

[colors.normal]
green = "#13FF0E"
blue = "#207ff0"
magenta = "#881798"
cyan = "#3A96DD"

[colors.bright]
green = "#8ae234"
blue = "#3B78FF"
cyan = "#61D6D6"

